# Generated by Django 4.1.3 on 2022-12-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_calories_delete_healthmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("users", models.CharField(max_length=50, null=True)),
                ("age", models.IntegerField(max_length=50, null=True)),
                ("height", models.IntegerField(max_length=50, null=True)),
                ("weight", models.IntegerField(max_length=50, null=True)),
                ("gender", models.CharField(max_length=50, null=True)),
                ("activity", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
