# Generated by Django 4.1.3 on 2022-12-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_diet_activity_alter_diet_age_alter_diet_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymassindex",
            name="users",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="calories",
            name="users",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
