# Generated by Django 4.1.3 on 2022-12-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_bodymassindex_users_calories_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bodymassindex",
            name="users",
        ),
        migrations.RemoveField(
            model_name="calories",
            name="users",
        ),
    ]
