# Generated by Django 4.1.3 on 2022-12-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_bodymassindex_users_remove_calories_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodymassindex",
            options={
                "verbose_name": "Индекс Массы Тела",
                "verbose_name_plural": "База ИМТ",
            },
        ),
        migrations.AlterModelOptions(
            name="calories",
            options={
                "verbose_name": "Дневное потребление калорий",
                "verbose_name_plural": "Дневное потребление калорий",
            },
        ),
        migrations.AlterModelOptions(
            name="diet",
            options={
                "verbose_name": "Общие сведения",
                "verbose_name_plural": "Общие сведения",
            },
        ),
    ]
